services:
  - type: web
    name: webapp-phonebook
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npm prune --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
